spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://web05.jeemoo.net:3306/uc?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: yuhe
    password: Yuhe@jeemoo909
  jpa:
    database: mysql
