spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/car_manager?characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    database: mysql
